steps:
  # Step 1: Checkout the code from the repository
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'git clone https://github.com/AttulKumar/Full-stack-app-with-CICD-'
  
  # Step 2: Install Node.js dependencies
  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm install'
      

options:
  logging: CLOUD_LOGGING_ONLY
