steps:
  # Step 1: Checkout the code from the repository
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'git clone https://github.com/AttulKumar/Full-stack-app-with-CICD-'
  
  # Step 2: Update package list and install nginx on the VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh web-server-react --zone us-central1-a	 --command "sudo apt update && sudo apt install -y nginx"
      

options:
  logging: CLOUD_LOGGING_ONLY
