steps:
  # Step 1: Checkout the code from the repository
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'git clone https://github.com/AttulKumar/Full-stack-app-with-CICD-'
  
  # Step 2: Update package list and install nginx on the VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh web-server-react --zone us-central1-a	 --command "sudo apt update"


    # Step 3: SSH into the VM and run the Node.js setup commands
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh backend01 --zone us-central1-f --command "
          cd /home/atulbusiness792_gmail_com/my-app &&
          npm init -y &&
          echo \"const express = require('express');\n\
          const app = express();\n\
          const port = 5000;\n\
          app.get('/', (req, res) => {\n\
            res.send('backend -1!');\n\
          });\n\
          app.listen(port, () => {\n\
            console.log('Example app listening on port ${port}');\n\
          });\" > index.js &&
          node index.js
        "
      

options:
  logging: CLOUD_LOGGING_ONLY
